# Generated by Django 4.2.23 on 2025-10-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('tara', models.CharField(blank=True, max_length=80, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('procent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('suma_fixa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_la', models.DateField(blank=True, null=True)),
                ('end_la', models.DateField(blank=True, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('tara', models.CharField(blank=True, max_length=80, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=160)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('gen', models.CharField(choices=[('unisex', 'Unisex'), ('femei', 'Femei'), ('barbati', 'Barbati')], default='unisex', max_length=10)),
                ('pret_baza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('activ', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produse', to='moto_shop.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produse', to='moto_shop.categorie')),
            ],
            options={
                'ordering': ['-creat_la'],
                'unique_together': {('brand', 'nume')},
            },
        ),
        migrations.CreateModel(
            name='VariantaProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produs', models.CharField(max_length=50, unique=True)),
                ('marime', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large')], default='M', max_length=5)),
                ('culoare', models.CharField(max_length=40)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.PositiveIntegerField(default=0)),
                ('greutate', models.PositiveIntegerField(blank=True, null=True)),
                ('disponibil_de_la', models.DateField(blank=True, null=True)),
                ('activ', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variante', to='moto_shop.discount')),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variante', to='moto_shop.furnizor')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variante', to='moto_shop.produs')),
            ],
            options={
                'ordering': ['produs', 'cod_produs'],
                'unique_together': {('produs', 'marime', 'culoare')},
            },
        ),
        migrations.CreateModel(
            name='ImagineProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('este_coperta', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='moto_shop.produs')),
            ],
            options={
                'ordering': ['produs', 'ordine'],
                'unique_together': {('produs', 'ordine')},
            },
        ),
    ]
