# Generated by Django 4.2.11 on 2025-11-19 12:01

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('tara', models.CharField(blank=True, max_length=80, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Brand-uri',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('culoare', models.CharField(blank=True, help_text='Hex color, ex: #FF5722', max_length=7, null=True)),
                ('icon_css', models.CharField(blank=True, help_text='FontAwesome class, ex: fa-solid fa-helmet-safety', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('procent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('suma_fixa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_la', models.DateField(blank=True, null=True)),
                ('end_la', models.DateField(blank=True, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Discounturi',
            },
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('tara', models.CharField(blank=True, max_length=80, null=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Furnizori',
                'ordering': ['nume'],
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=160)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('gen', models.CharField(choices=[('unisex', 'Unisex'), ('femei', 'Femei'), ('barbati', 'Barbati')], default='unisex', max_length=10)),
                ('pret_baza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('activ', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produse', to='moto_shop.brand')),
                ('categorii', models.ManyToManyField(blank=True, related_name='produse', to='moto_shop.categorie')),
            ],
            options={
                'verbose_name_plural': 'Produse',
                'ordering': ['-creat_la'],
                'unique_together': {('brand', 'nume')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nume', models.CharField(help_text='Numele complet afișat pe site.', max_length=100)),
                ('telefon', models.CharField(blank=True, help_text='Telefon de contact.', max_length=20)),
                ('tara', models.CharField(blank=True, max_length=50)),
                ('judet', models.CharField(blank=True, max_length=50)),
                ('localitate', models.CharField(blank=True, max_length=80)),
                ('strada', models.CharField(blank=True, max_length=120)),
                ('nr_strada', models.IntegerField(blank=True, null=True)),
                ('cod_postal', models.IntegerField(blank=True, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Utilizatori',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VariantaProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produs', models.CharField(max_length=50, unique=True)),
                ('marime', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large')], default='M', max_length=5)),
                ('culoare', models.CharField(max_length=40)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoc', models.PositiveIntegerField(default=0)),
                ('greutate', models.PositiveIntegerField(blank=True, null=True)),
                ('disponibil_de_la', models.DateField(blank=True, null=True)),
                ('activ', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variante', to='moto_shop.discount')),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variante', to='moto_shop.furnizor')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variante', to='moto_shop.produs')),
            ],
            options={
                'verbose_name_plural': 'VarianteProdus',
                'ordering': ['produs', 'cod_produs'],
                'unique_together': {('produs', 'marime', 'culoare')},
            },
        ),
        migrations.CreateModel(
            name='ImagineProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('este_coperta', models.BooleanField(default=False)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='moto_shop.produs')),
            ],
            options={
                'verbose_name_plural': 'Imaginiprodus',
                'ordering': ['produs', 'ordine'],
                'unique_together': {('produs', 'ordine')},
            },
        ),
    ]
