# Generated by Django 4.2.23 on 2025-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare',
            field=models.CharField(blank=True, help_text='Hex color, ex: #FF5722', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icon_css',
            field=models.CharField(blank=True, help_text='FontAwesome class, ex: fa-solid fa-helmet-safety', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
