# Generated by Django 4.2.11 on 2025-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
