# Generated by Django 4.2.23 on 2025-11-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0002_categorie_culoare_categorie_icon_css_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
