# Generated by Django 4.2.23 on 2025-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0003_alter_categorie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='categorie',
        ),
        migrations.AddField(
            model_name='produs',
            name='categorii',
            field=models.ManyToManyField(blank=True, related_name='produse', to='moto_shop.categorie'),
        ),
    ]
