# Generated by Django 4.2.11 on 2025-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0003_vizualizare_promotie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotie',
            options={'permissions': (('vizualizeaza_oferta', 'Poate vizualiza oferta speciala'),), 'verbose_name_plural': 'Promotii'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
    ]
