# Generated by Django 4.2.23 on 2025-11-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto_shop', '0004_remove_produs_categorie_produs_categorii'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['nume'], 'verbose_name_plural': 'Brand-uri'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'Discounturi'},
        ),
        migrations.AlterModelOptions(
            name='furnizor',
            options={'ordering': ['nume'], 'verbose_name_plural': 'Furnizori'},
        ),
        migrations.AlterModelOptions(
            name='imagineprodus',
            options={'ordering': ['produs', 'ordine'], 'verbose_name_plural': 'Imaginiprodus'},
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'ordering': ['-creat_la'], 'verbose_name_plural': 'Produse'},
        ),
        migrations.AlterModelOptions(
            name='variantaprodus',
            options={'ordering': ['produs', 'cod_produs'], 'verbose_name_plural': 'VarianteProdus'},
        ),
    ]
